
services:

  backend:
    build:
      context: .
      dockerfile: .docker/dev/backend/Dockerfile
    restart:        unless-stopped
    tty:            true
    volumes:
      - ./:/var/www
    networks:
      - tayyab
  
  frontend:
    build:
      context: .
      dockerfile: .docker/dev/frontend/Dockerfile
    restart:        unless-stopped
    tty:            true
    volumes:
      - ./:/var/www
    networks:
      - tayyab
    ports:
        - "7088:80"
    

  database:
    image: mariadb
    container_name: devdb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./.dbdata:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "33066:3306"
    networks:
      - tayyab

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "63799:6379"
    networks:
      - tayyab

  node:
    build:
      context: .
      dockerfile: .docker/dev/node/Dockerfile 
    tty: true
    networks:
      - tayyab
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www

  horizon:
    build:
      context: .
      dockerfile: .docker/dev/backend/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - tayyab
    depends_on:
      - redis
      - database
    command: php artisan horizon

  scheduler:
    build:
      context: .
      dockerfile: .docker/dev/backend/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - tayyab
    depends_on:
      - database
    command: php artisan schedule:work
  
  mailhog:
    image:          mailhog/mailhog
    restart:        unless-stopped
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - tayyab


networks:
  tayyab:
    driver: bridge