

services:
  backend:
    platform: linux/amd64
    image: registry.digitalocean.com/myregistrytayyab/mldabackend:latest
    build:
      context: ../../
      dockerfile: .docker/prod/backend/Dockerfile
    restart:        unless-stopped
    tty:            true
    networks:
      - tayyab
  
  frontend:
    platform: linux/amd64
    image: registry.digitalocean.com/myregistrytayyab/mldafrontend:latest
    build:
      context: ../../
      dockerfile: .docker/prod/frontend/Dockerfile
    restart:        unless-stopped
    tty:            true
    networks:
      - tayyab
    ports:
        - "7088:80"
    depends_on:
      - backend
  
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - tayyab
  
  database:
    image: mariadb
    container_name: devdb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./.dbdata:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "33066:3306"
    networks:
      - tayyab
  
  node:
    image: node:22-alpine
    working_dir: /var/www
    tty: true
    volumes:
      - ./:/var/www
    environment:
      - SKIP_WAYFINDER=1
    networks:
      - tayyab
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run build"

networks:
  tayyab: